### ISSUE TITLE
Test plugin

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-TextAnalysis#2]
I had to update the underlying text analysis service and need you to make sure the plugin successfully upgrades, configures, and displays results without errors. I'm not sure if you've ever used this plugin, but the new results should look similar the previous results.

To test this, you'll need to enter your IBM Bluemix service credentials into plugin configuration. Then, go to an item show page and, in the sidebar under "Text Analysis", choose an element that contains a lot of text and click "Analyze this Element". It should take you to a tabbed page containing a slew of information about your selected text. Make sure there are no errors in those tabs and make note of any confusing areas that I could clarify. For best results test this on a handful of real articles, long and short.

**Comment by mebrett** [comment]
Two things that I noticed right away: the new service includes emotion as well as sentiment in the entity tab (just means I have to update the screenshot). Also on the entity tab, it's having some trouble with aspects of the text it recognizes as entities which are numeric/quantities:


![screen shot 2017-03-22 at 4 58 40 pm](https://cloud.githubusercontent.com/assets/2314070/24220497/d1d99a88-0f20-11e7-85e1-de9a9d7974ef.png)

![screen shot 2017-03-22 at 4 11 58 pm](https://cloud.githubusercontent.com/assets/2314070/24220492/c7c60270-0f20-11e7-92df-a27420c3203d.png)

**Comment by mebrett** [comment]
Latest commit fixed the display issue with the Quantity and I like the addition of options for what to analyze.
