### ISSUE TITLE
Parse error upon opening plugin from admin

### ISSUE THREAD

**Issue by sheilabrennan** [omeka/plugin-TextAnalysis#3]
Clicking on the plugin's tab in the left nav bar reveals this error:
Parse error: syntax error, unexpected '[' in /websites/911devel/www/plugins/TextAnalysis/controllers/CorporaController.php on line 53

Not sure if this is an actual bug or a problem with how things are set up on this dev server. 

Plugin is up to date.

**Comment by jimsafley** [comment]
Should work now
